CC = gcc
CXX = g++

CFGLAGS = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

http-client: 


.PHONY: clean
clean:
	rm -f *.0 *~ *.html *.jpg a.out core http-client

.PHONY: all
all: clean http-client 
